<?php

$lang = array(

	'other' => '其他',
	'app_connect_ok' => '通訊成功',
	'app_connect_false' => '通訊失敗',

	'note_deleteuser' => '刪除會員',
	'note_renameuser' => '重新命名會員',
	'note_deletefriend' => '刪除好友',
	'note_gettag' => '取得 TAG',
	'note_getcreditsettings' => '取得應用程式積分設定',
	'note_updatecreditsettings' => '更新應用程式積分設定',
	'note_updateclient' => '更新應用程式快取',
	'note_updatepw' => '更新會員密碼',
	'note_updatebadwords' => '更新詞語過濾列表',
	'note_updatehosts' => '更新網域名稱解析列表',
	'note_updateapps' => '更新應用列表',
	'note_updatetagtemplate' => '更新標籤模板設定',
	'note_list' => '通知列表',
	'note_test' => '測試',
	'note_delete' => '刪除',
	'note_succeed' => '通知成功',
	'note_na' => '未通知',
	'note_false' => '通知失敗',
	'note_times' => '次',

	'pm_from' => '來自',
	'pm_to' => '發送到',
	'pm_system' => '系統訊息',
	'pm_date' => '時間',
	'pm_daterange_1' => '今天',
	'pm_daterange_2' => '昨天',
	'pm_daterange_3' => '前天',
	'pm_daterange_4' => '上週',
	'pm_daterange_5' => '更早',
	'pm_notitle' => '[無標題]',

	'user_add' => '新增會員',
	'user_delete' => '刪除會員',
	'login' => '登入',
	'logout' => '登出',
	'app_add' => '新增新應用程式',
	'app_delete' => '刪除應用程式',
	'app_edit' => '編輯應用程式',
	'setting_update' => '更新基本設定',
	'setting_register_update' => '更新註冊設定',
	'pm_send' => '發送公共訊息',
	'pm_delete' => '刪除公共訊息',
	'pm_clear' => '清理短訊',
	'badword_add' => '新增詞語過濾',
	'badword_delete' => '刪除詞語過濾',
	'admin_add' => '新增管理員',
	'admin_pw_edit' => '修改創始人密碼',
	'admin_priv_edit' => '修改管理員權限',
	'domain_add' => '新增網域名稱解析',
	'domain_delete' => '刪除網域名稱解析',
	'credit_addexchange' => '更新積分兌換方案',
	'credit_deleteexchange' => '刪除積分兌換方案',
	'credit_sync' => '同步應用程式的積分設定',
	'db_export' => '備份資料',
	'db_import' => '恢復資料',
	'db_delete' => '刪除資料',
	'note_delete' => '刪除通知',
	'note_send' => '補發通知',
	'dumpfile_exists' => '備份存在',
	'dumpfile_not_exists' => '備份不存在',
);